version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: habit-tracker-cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=HabitTracker
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - habit-network

  backend:
    build: ./backend
    container_name: habit-tracker-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - habit-network

volumes:
  cassandra_data:

networks:
  habit-network:
    driver: bridge